In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])

In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
b = np.array([[1,2,3],[4,5,6]])

In [8]:
print(b.shape)

(2, 3)


In [9]:
print(b)

[[1 2 3]
 [4 5 6]]


In [10]:
a = np.zeros((3,3))
print(a)
print(a.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)


### Array of constants

In [11]:
c = np.full((2,3),5)
print(c)

[[5 5 5]
 [5 5 5]]


### Identity matrix

In [12]:
d = np.eye(4)
print(d)
print(d.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)


### Random matrix

In [14]:
randomMatrix = np.random.random((2,3))

In [15]:
print(randomMatrix)

[[0.2643366  0.00729856 0.84068935]
 [0.13731246 0.43770464 0.19756166]]


In [16]:
print(randomMatrix[:,1])

[0.00729856 0.43770464]


In [19]:
z = np.zeros((3,3),dtype = int)
print(z)
z[1,:] = 5
z[:,-1] = 7
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 7]
 [5 5 7]
 [0 0 7]]


### Mathematical operation

In [21]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x+y)

[[ 6  8]
 [10 12]]


In [22]:
print(x*y)

[[ 5 12]
 [21 32]]


In [23]:
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]


### Matrix multiplication (dot products)

In [24]:
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [25]:
print(x.dot(y))
print(np.dot(x,y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


### Matrix Multiplication of two vectors

In [26]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])

print(a.dot(b))

30


### Stacking of arrays

In [29]:
print(a)
b = b**2
print(b)

[1 2 3 4]
[ 1  4  9 16]


In [30]:
np.stack((a,b),axis = 1)

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16]])

### Random Module

In [31]:
a = np.arange(10) + 5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [32]:
np.random.shuffle(a)
print(a)

[ 6 13 10  5 12  8 11  7 14  9]


In [33]:
a = np.random.rand(2,3)
print(a)

[[0.15454667 0.60880543 0.89084269]
 [0.74381919 0.79153343 0.49229628]]


In [34]:
a = np.random.randint(5,10,3)
print(a)

[9 9 6]


### Statistics

In [35]:
a = np.array([[1,2,3,4],[7,6,2,0]])
print(a)

[[1 2 3 4]
 [7 6 2 0]]


In [37]:
print(np.min(a,axis =0))
print(np.min(a,axis =1))

[1 2 2 0]
[1 0]


In [38]:
print(np.mean(a))

3.125


In [39]:
b= np.array([1,2,3,4,5])
print(np.mean(b))

3.0


In [40]:
print(np.mean(b,axis=0))

3.0


In [42]:
print(np.median(a))

2.5


In [45]:
c = np.array([1,5,4,2,0])

In [46]:
w = np.array([1,2,3,4,5])
print(np.average(c,weights = w))

2.066666666666667


## Standard Deviation

In [47]:
u = np.mean(c)

In [48]:
mystd = np.sqrt(np.mean(abs(c-u)**2))

In [49]:
print(mystd)

1.854723699099141


In [50]:
dev = np.std(c)
print(dev)

1.854723699099141


### Variance

In [52]:
print(mystd**2)

3.440000000000001


In [53]:
print(np.var(c))

3.4400000000000004
